[package]
name = "aoc-rust"
version = "0.0.0"
edition = "2021"

[dependencies]

[dev-dependencies]
test-case = "3.3.1"

[profile.dev]
opt-level = 2

[profile.release]
debug = true
overflow-checks = true
